// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/account/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/account/handler.go -destination=internal/handler/account/mocks/mock_account_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockaccountService is a mock of accountService interface.
type MockaccountService struct {
	ctrl     *gomock.Controller
	recorder *MockaccountServiceMockRecorder
	isgomock struct{}
}

// MockaccountServiceMockRecorder is the mock recorder for MockaccountService.
type MockaccountServiceMockRecorder struct {
	mock *MockaccountService
}

// NewMockaccountService creates a new mock instance.
func NewMockaccountService(ctrl *gomock.Controller) *MockaccountService {
	mock := &MockaccountService{ctrl: ctrl}
	mock.recorder = &MockaccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccountService) EXPECT() *MockaccountServiceMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockaccountService) AddMember(ctx context.Context, accountID, username string, share float64) ([]model.AccountMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", ctx, accountID, username, share)
	ret0, _ := ret[0].([]model.AccountMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMember indicates an expected call of AddMember.
func (mr *MockaccountServiceMockRecorder) AddMember(ctx, accountID, username, share any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockaccountService)(nil).AddMember), ctx, accountID, username, share)
}

// CreateAccount mocks base method.
func (m *MockaccountService) CreateAccount(ctx context.Context, ownerID string, req model.CreateAccountReq) (model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, ownerID, req)
	ret0, _ := ret[0].(model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockaccountServiceMockRecorder) CreateAccount(ctx, ownerID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockaccountService)(nil).CreateAccount), ctx, ownerID, req)
}

// DeleteAccount mocks base method.
func (m *MockaccountService) DeleteAccount(ctx context.Context, requesterID, accountID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, requesterID, accountID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockaccountServiceMockRecorder) DeleteAccount(ctx, requesterID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockaccountService)(nil).DeleteAccount), ctx, requesterID, accountID)
}

// GetByID mocks base method.
func (m *MockaccountService) GetByID(ctx context.Context, accountID string) (model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, accountID)
	ret0, _ := ret[0].(model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockaccountServiceMockRecorder) GetByID(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockaccountService)(nil).GetByID), ctx, accountID)
}

// GetMembers mocks base method.
func (m *MockaccountService) GetMembers(ctx context.Context, accountID string) ([]model.AccountMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembers", ctx, accountID)
	ret0, _ := ret[0].([]model.AccountMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembers indicates an expected call of GetMembers.
func (mr *MockaccountServiceMockRecorder) GetMembers(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembers", reflect.TypeOf((*MockaccountService)(nil).GetMembers), ctx, accountID)
}

// ListBalancesByUser mocks base method.
func (m *MockaccountService) ListBalancesByUser(ctx context.Context, userID, displayCurrency string) (map[string]model.AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBalancesByUser", ctx, userID, displayCurrency)
	ret0, _ := ret[0].(map[string]model.AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBalancesByUser indicates an expected call of ListBalancesByUser.
func (mr *MockaccountServiceMockRecorder) ListBalancesByUser(ctx, userID, displayCurrency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBalancesByUser", reflect.TypeOf((*MockaccountService)(nil).ListBalancesByUser), ctx, userID, displayCurrency)
}

// ListByUser mocks base method.
func (m *MockaccountService) ListByUser(ctx context.Context, userID string) ([]model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockaccountServiceMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockaccountService)(nil).ListByUser), ctx, userID)
}

// RemoveMember mocks base method.
func (m *MockaccountService) RemoveMember(ctx context.Context, requesterID, accountID, memberUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, requesterID, accountID, memberUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockaccountServiceMockRecorder) RemoveMember(ctx, requesterID, accountID, memberUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockaccountService)(nil).RemoveMember), ctx, requesterID, accountID, memberUserID)
}

// UpdateAccount mocks base method.
func (m *MockaccountService) UpdateAccount(ctx context.Context, accountID string, req model.UpdateAccountReq) (model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, accountID, req)
	ret0, _ := ret[0].(model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockaccountServiceMockRecorder) UpdateAccount(ctx, accountID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockaccountService)(nil).UpdateAccount), ctx, accountID, req)
}

// UpdateMember mocks base method.
func (m *MockaccountService) UpdateMember(ctx context.Context, accountID, memberUserID string, share float64) ([]model.AccountMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMember", ctx, accountID, memberUserID, share)
	ret0, _ := ret[0].([]model.AccountMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMember indicates an expected call of UpdateMember.
func (mr *MockaccountServiceMockRecorder) UpdateMember(ctx, accountID, memberUserID, share any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMember", reflect.TypeOf((*MockaccountService)(nil).UpdateMember), ctx, accountID, memberUserID, share)
}

// MockuserSource is a mock of userSource interface.
type MockuserSource struct {
	ctrl     *gomock.Controller
	recorder *MockuserSourceMockRecorder
	isgomock struct{}
}

// MockuserSourceMockRecorder is the mock recorder for MockuserSource.
type MockuserSourceMockRecorder struct {
	mock *MockuserSource
}

// NewMockuserSource creates a new mock instance.
func NewMockuserSource(ctrl *gomock.Controller) *MockuserSource {
	mock := &MockuserSource{ctrl: ctrl}
	mock.recorder = &MockuserSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserSource) EXPECT() *MockuserSourceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockuserSource) GetByID(ctx context.Context, id string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockuserSourceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockuserSource)(nil).GetByID), ctx, id)
}
