// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/invite/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/invite/handler.go -destination=internal/handler/invite/mocks/mock_invite_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	service "github.com/co-wallet/backend/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockinviteService is a mock of inviteService interface.
type MockinviteService struct {
	ctrl     *gomock.Controller
	recorder *MockinviteServiceMockRecorder
	isgomock struct{}
}

// MockinviteServiceMockRecorder is the mock recorder for MockinviteService.
type MockinviteServiceMockRecorder struct {
	mock *MockinviteService
}

// NewMockinviteService creates a new mock instance.
func NewMockinviteService(ctrl *gomock.Controller) *MockinviteService {
	mock := &MockinviteService{ctrl: ctrl}
	mock.recorder = &MockinviteServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinviteService) EXPECT() *MockinviteServiceMockRecorder {
	return m.recorder
}

// AcceptInvite mocks base method.
func (m *MockinviteService) AcceptInvite(ctx context.Context, req service.AcceptInviteReq) (model.User, service.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptInvite", ctx, req)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(service.TokenPair)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AcceptInvite indicates an expected call of AcceptInvite.
func (mr *MockinviteServiceMockRecorder) AcceptInvite(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptInvite", reflect.TypeOf((*MockinviteService)(nil).AcceptInvite), ctx, req)
}

// CreateInvite mocks base method.
func (m *MockinviteService) CreateInvite(ctx context.Context, email, createdBy string) (model.Invite, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvite", ctx, email, createdBy)
	ret0, _ := ret[0].(model.Invite)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateInvite indicates an expected call of CreateInvite.
func (mr *MockinviteServiceMockRecorder) CreateInvite(ctx, email, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvite", reflect.TypeOf((*MockinviteService)(nil).CreateInvite), ctx, email, createdBy)
}

// ListInvites mocks base method.
func (m *MockinviteService) ListInvites(ctx context.Context) ([]model.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvites", ctx)
	ret0, _ := ret[0].([]model.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvites indicates an expected call of ListInvites.
func (mr *MockinviteServiceMockRecorder) ListInvites(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvites", reflect.TypeOf((*MockinviteService)(nil).ListInvites), ctx)
}

// ValidateToken mocks base method.
func (m *MockinviteService) ValidateToken(ctx context.Context, token string) (*model.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, token)
	ret0, _ := ret[0].(*model.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockinviteServiceMockRecorder) ValidateToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockinviteService)(nil).ValidateToken), ctx, token)
}
