// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/mock_import_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockimportService is a mock of importService interface.
type MockimportService struct {
	ctrl     *gomock.Controller
	recorder *MockimportServiceMockRecorder
	isgomock struct{}
}

// MockimportServiceMockRecorder is the mock recorder for MockimportService.
type MockimportServiceMockRecorder struct {
	mock *MockimportService
}

// NewMockimportService creates a new mock instance.
func NewMockimportService(ctrl *gomock.Controller) *MockimportService {
	mock := &MockimportService{ctrl: ctrl}
	mock.recorder = &MockimportServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockimportService) EXPECT() *MockimportServiceMockRecorder {
	return m.recorder
}

// Availability mocks base method.
func (m *MockimportService) Availability(arg0 context.Context, arg1 string) (model.ImportAvailability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Availability", arg0, arg1)
	ret0, _ := ret[0].(model.ImportAvailability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Availability indicates an expected call of Availability.
func (mr *MockimportServiceMockRecorder) Availability(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Availability", reflect.TypeOf((*MockimportService)(nil).Availability), arg0, arg1)
}

// Configure mocks base method.
func (m *MockimportService) Configure(arg0 context.Context, arg1, arg2 string, arg3 map[string]model.AccountKind, arg4, arg5 map[string]string) (model.ImportPreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Configure", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(model.ImportPreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Configure indicates an expected call of Configure.
func (mr *MockimportServiceMockRecorder) Configure(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Configure", reflect.TypeOf((*MockimportService)(nil).Configure), arg0, arg1, arg2, arg3, arg4, arg5)
}

// Confirm mocks base method.
func (m *MockimportService) Confirm(arg0 context.Context, arg1, arg2 string, arg3, arg4 bool) (model.ImportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(model.ImportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Confirm indicates an expected call of Confirm.
func (mr *MockimportServiceMockRecorder) Confirm(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockimportService)(nil).Confirm), arg0, arg1, arg2, arg3, arg4)
}

// Preview mocks base method.
func (m *MockimportService) Preview(arg0 context.Context, arg1 string, arg2 io.Reader, arg3 model.ImportMode) (model.ImportPreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preview", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(model.ImportPreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Preview indicates an expected call of Preview.
func (mr *MockimportServiceMockRecorder) Preview(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preview", reflect.TypeOf((*MockimportService)(nil).Preview), arg0, arg1, arg2, arg3)
}
