// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/tag/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/tag/handler.go -destination=internal/handler/tag/mocks/mock_tag_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MocktagService is a mock of tagService interface.
type MocktagService struct {
	ctrl     *gomock.Controller
	recorder *MocktagServiceMockRecorder
	isgomock struct{}
}

// MocktagServiceMockRecorder is the mock recorder for MocktagService.
type MocktagServiceMockRecorder struct {
	mock *MocktagService
}

// NewMocktagService creates a new mock instance.
func NewMocktagService(ctrl *gomock.Controller) *MocktagService {
	mock := &MocktagService{ctrl: ctrl}
	mock.recorder = &MocktagServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktagService) EXPECT() *MocktagServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MocktagService) Delete(ctx context.Context, userID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MocktagServiceMockRecorder) Delete(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MocktagService)(nil).Delete), ctx, userID, id)
}

// List mocks base method.
func (m *MocktagService) List(ctx context.Context, userID, q string) ([]model.TagWithCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, q)
	ret0, _ := ret[0].([]model.TagWithCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MocktagServiceMockRecorder) List(ctx, userID, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MocktagService)(nil).List), ctx, userID, q)
}

// Rename mocks base method.
func (m *MocktagService) Rename(ctx context.Context, userID, id, name string) (model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", ctx, userID, id, name)
	ret0, _ := ret[0].(model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rename indicates an expected call of Rename.
func (mr *MocktagServiceMockRecorder) Rename(ctx, userID, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MocktagService)(nil).Rename), ctx, userID, id, name)
}
