// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/admin/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/admin/handler.go -destination=internal/handler/admin/mocks/mock_admin_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	service "github.com/co-wallet/backend/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockadminService is a mock of adminService interface.
type MockadminService struct {
	ctrl     *gomock.Controller
	recorder *MockadminServiceMockRecorder
	isgomock struct{}
}

// MockadminServiceMockRecorder is the mock recorder for MockadminService.
type MockadminServiceMockRecorder struct {
	mock *MockadminService
}

// NewMockadminService creates a new mock instance.
func NewMockadminService(ctrl *gomock.Controller) *MockadminService {
	mock := &MockadminService{ctrl: ctrl}
	mock.recorder = &MockadminServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockadminService) EXPECT() *MockadminServiceMockRecorder {
	return m.recorder
}

// CreateCurrency mocks base method.
func (m *MockadminService) CreateCurrency(ctx context.Context, req service.CreateCurrencyReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCurrency", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCurrency indicates an expected call of CreateCurrency.
func (mr *MockadminServiceMockRecorder) CreateCurrency(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCurrency", reflect.TypeOf((*MockadminService)(nil).CreateCurrency), ctx, req)
}

// GetUser mocks base method.
func (m *MockadminService) GetUser(ctx context.Context, id string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockadminServiceMockRecorder) GetUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockadminService)(nil).GetUser), ctx, id)
}

// ListAllCurrencies mocks base method.
func (m *MockadminService) ListAllCurrencies(ctx context.Context) ([]model.CurrencyWithRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllCurrencies", ctx)
	ret0, _ := ret[0].([]model.CurrencyWithRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllCurrencies indicates an expected call of ListAllCurrencies.
func (mr *MockadminServiceMockRecorder) ListAllCurrencies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllCurrencies", reflect.TypeOf((*MockadminService)(nil).ListAllCurrencies), ctx)
}

// ListUsers mocks base method.
func (m *MockadminService) ListUsers(ctx context.Context) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockadminServiceMockRecorder) ListUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockadminService)(nil).ListUsers), ctx)
}

// RefreshRates mocks base method.
func (m *MockadminService) RefreshRates(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshRates", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshRates indicates an expected call of RefreshRates.
func (mr *MockadminServiceMockRecorder) RefreshRates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshRates", reflect.TypeOf((*MockadminService)(nil).RefreshRates), ctx)
}

// UpdateCurrency mocks base method.
func (m *MockadminService) UpdateCurrency(ctx context.Context, code string, req service.UpdateCurrencyReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCurrency", ctx, code, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCurrency indicates an expected call of UpdateCurrency.
func (mr *MockadminServiceMockRecorder) UpdateCurrency(ctx, code, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCurrency", reflect.TypeOf((*MockadminService)(nil).UpdateCurrency), ctx, code, req)
}

// UpdateUser mocks base method.
func (m *MockadminService) UpdateUser(ctx context.Context, id string, req service.AdminUpdateUserReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockadminServiceMockRecorder) UpdateUser(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockadminService)(nil).UpdateUser), ctx, id, req)
}
