// Code generated by MockGen. DO NOT EDIT.
// Source: currency.go
//
// Generated by this command:
//
//	mockgen -source=currency.go -destination=mocks/mock_currency_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockcurrencyRepo is a mock of currencyRepo interface.
type MockcurrencyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockcurrencyRepoMockRecorder
	isgomock struct{}
}

// MockcurrencyRepoMockRecorder is the mock recorder for MockcurrencyRepo.
type MockcurrencyRepoMockRecorder struct {
	mock *MockcurrencyRepo
}

// NewMockcurrencyRepo creates a new mock instance.
func NewMockcurrencyRepo(ctrl *gomock.Controller) *MockcurrencyRepo {
	mock := &MockcurrencyRepo{ctrl: ctrl}
	mock.recorder = &MockcurrencyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcurrencyRepo) EXPECT() *MockcurrencyRepoMockRecorder {
	return m.recorder
}

// GetRate mocks base method.
func (m *MockcurrencyRepo) GetRate(ctx context.Context, base, quote string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRate", ctx, base, quote)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRate indicates an expected call of GetRate.
func (mr *MockcurrencyRepoMockRecorder) GetRate(ctx, base, quote any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRate", reflect.TypeOf((*MockcurrencyRepo)(nil).GetRate), ctx, base, quote)
}

// ListActive mocks base method.
func (m *MockcurrencyRepo) ListActive(ctx context.Context, extraCodes []string) ([]model.CurrencyWithRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx, extraCodes)
	ret0, _ := ret[0].([]model.CurrencyWithRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockcurrencyRepoMockRecorder) ListActive(ctx, extraCodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockcurrencyRepo)(nil).ListActive), ctx, extraCodes)
}

// UpsertRates mocks base method.
func (m *MockcurrencyRepo) UpsertRates(ctx context.Context, base string, rates map[string]float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRates", ctx, base, rates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRates indicates an expected call of UpsertRates.
func (mr *MockcurrencyRepoMockRecorder) UpsertRates(ctx, base, rates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRates", reflect.TypeOf((*MockcurrencyRepo)(nil).UpsertRates), ctx, base, rates)
}
