// Code generated by MockGen. DO NOT EDIT.
// Source: admin.go
//
// Generated by this command:
//
//	mockgen -source=admin.go -destination=mocks/mock_admin_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockadminRepo is a mock of adminRepo interface.
type MockadminRepo struct {
	ctrl     *gomock.Controller
	recorder *MockadminRepoMockRecorder
	isgomock struct{}
}

// MockadminRepoMockRecorder is the mock recorder for MockadminRepo.
type MockadminRepoMockRecorder struct {
	mock *MockadminRepo
}

// NewMockadminRepo creates a new mock instance.
func NewMockadminRepo(ctrl *gomock.Controller) *MockadminRepo {
	mock := &MockadminRepo{ctrl: ctrl}
	mock.recorder = &MockadminRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockadminRepo) EXPECT() *MockadminRepoMockRecorder {
	return m.recorder
}

// CreateCurrency mocks base method.
func (m *MockadminRepo) CreateCurrency(ctx context.Context, c model.Currency) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCurrency", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCurrency indicates an expected call of CreateCurrency.
func (mr *MockadminRepoMockRecorder) CreateCurrency(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCurrency", reflect.TypeOf((*MockadminRepo)(nil).CreateCurrency), ctx, c)
}

// GetUser mocks base method.
func (m *MockadminRepo) GetUser(ctx context.Context, id string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockadminRepoMockRecorder) GetUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockadminRepo)(nil).GetUser), ctx, id)
}

// ListAllCurrencies mocks base method.
func (m *MockadminRepo) ListAllCurrencies(ctx context.Context) ([]model.CurrencyWithRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllCurrencies", ctx)
	ret0, _ := ret[0].([]model.CurrencyWithRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllCurrencies indicates an expected call of ListAllCurrencies.
func (mr *MockadminRepoMockRecorder) ListAllCurrencies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllCurrencies", reflect.TypeOf((*MockadminRepo)(nil).ListAllCurrencies), ctx)
}

// ListUsers mocks base method.
func (m *MockadminRepo) ListUsers(ctx context.Context) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockadminRepoMockRecorder) ListUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockadminRepo)(nil).ListUsers), ctx)
}

// RateKnown mocks base method.
func (m *MockadminRepo) RateKnown(ctx context.Context, code string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RateKnown", ctx, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RateKnown indicates an expected call of RateKnown.
func (mr *MockadminRepoMockRecorder) RateKnown(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RateKnown", reflect.TypeOf((*MockadminRepo)(nil).RateKnown), ctx, code)
}

// UpdateCurrency mocks base method.
func (m *MockadminRepo) UpdateCurrency(ctx context.Context, code string, patch model.CurrencyPatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCurrency", ctx, code, patch)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCurrency indicates an expected call of UpdateCurrency.
func (mr *MockadminRepoMockRecorder) UpdateCurrency(ctx, code, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCurrency", reflect.TypeOf((*MockadminRepo)(nil).UpdateCurrency), ctx, code, patch)
}

// UpdateUser mocks base method.
func (m *MockadminRepo) UpdateUser(ctx context.Context, id string, patch model.AdminUserPatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, id, patch)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockadminRepoMockRecorder) UpdateUser(ctx, id, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockadminRepo)(nil).UpdateUser), ctx, id, patch)
}

// MockratesRefresher is a mock of ratesRefresher interface.
type MockratesRefresher struct {
	ctrl     *gomock.Controller
	recorder *MockratesRefresherMockRecorder
	isgomock struct{}
}

// MockratesRefresherMockRecorder is the mock recorder for MockratesRefresher.
type MockratesRefresherMockRecorder struct {
	mock *MockratesRefresher
}

// NewMockratesRefresher creates a new mock instance.
func NewMockratesRefresher(ctrl *gomock.Controller) *MockratesRefresher {
	mock := &MockratesRefresher{ctrl: ctrl}
	mock.recorder = &MockratesRefresherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockratesRefresher) EXPECT() *MockratesRefresherMockRecorder {
	return m.recorder
}

// FetchAndStoreRates mocks base method.
func (m *MockratesRefresher) FetchAndStoreRates(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAndStoreRates", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// FetchAndStoreRates indicates an expected call of FetchAndStoreRates.
func (mr *MockratesRefresherMockRecorder) FetchAndStoreRates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAndStoreRates", reflect.TypeOf((*MockratesRefresher)(nil).FetchAndStoreRates), ctx)
}
