// Code generated by MockGen. DO NOT EDIT.
// Source: invite.go
//
// Generated by this command:
//
//	mockgen -source=invite.go -destination=mocks/mock_invite_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockinviteRepo is a mock of inviteRepo interface.
type MockinviteRepo struct {
	ctrl     *gomock.Controller
	recorder *MockinviteRepoMockRecorder
	isgomock struct{}
}

// MockinviteRepoMockRecorder is the mock recorder for MockinviteRepo.
type MockinviteRepoMockRecorder struct {
	mock *MockinviteRepo
}

// NewMockinviteRepo creates a new mock instance.
func NewMockinviteRepo(ctrl *gomock.Controller) *MockinviteRepo {
	mock := &MockinviteRepo{ctrl: ctrl}
	mock.recorder = &MockinviteRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinviteRepo) EXPECT() *MockinviteRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockinviteRepo) Create(ctx context.Context, inv model.Invite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, inv)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockinviteRepoMockRecorder) Create(ctx, inv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockinviteRepo)(nil).Create), ctx, inv)
}

// GetByToken mocks base method.
func (m *MockinviteRepo) GetByToken(ctx context.Context, token string) (*model.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, token)
	ret0, _ := ret[0].(*model.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockinviteRepoMockRecorder) GetByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockinviteRepo)(nil).GetByToken), ctx, token)
}

// ListAll mocks base method.
func (m *MockinviteRepo) ListAll(ctx context.Context) ([]model.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]model.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockinviteRepoMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockinviteRepo)(nil).ListAll), ctx)
}

// MarkUsed mocks base method.
func (m *MockinviteRepo) MarkUsed(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUsed", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUsed indicates an expected call of MarkUsed.
func (mr *MockinviteRepoMockRecorder) MarkUsed(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUsed", reflect.TypeOf((*MockinviteRepo)(nil).MarkUsed), ctx, token)
}

// MockinviteUserRepo is a mock of inviteUserRepo interface.
type MockinviteUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockinviteUserRepoMockRecorder
	isgomock struct{}
}

// MockinviteUserRepoMockRecorder is the mock recorder for MockinviteUserRepo.
type MockinviteUserRepoMockRecorder struct {
	mock *MockinviteUserRepo
}

// NewMockinviteUserRepo creates a new mock instance.
func NewMockinviteUserRepo(ctrl *gomock.Controller) *MockinviteUserRepo {
	mock := &MockinviteUserRepo{ctrl: ctrl}
	mock.recorder = &MockinviteUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinviteUserRepo) EXPECT() *MockinviteUserRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockinviteUserRepo) Create(ctx context.Context, u model.User) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, u)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockinviteUserRepoMockRecorder) Create(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockinviteUserRepo)(nil).Create), ctx, u)
}
