// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/co-wallet/backend/internal/service (interfaces: TagRepo)
//
// Generated by this command:
//
//	mockgen -destination=internal/service/mocks/mock_tag_repo.go -package=mocks github.com/co-wallet/backend/internal/service TagRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockTagRepo is a mock of TagRepo interface.
type MockTagRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepoMockRecorder
	isgomock struct{}
}

// MockTagRepoMockRecorder is the mock recorder for MockTagRepo.
type MockTagRepoMockRecorder struct {
	mock *MockTagRepo
}

// NewMockTagRepo creates a new mock instance.
func NewMockTagRepo(ctrl *gomock.Controller) *MockTagRepo {
	mock := &MockTagRepo{ctrl: ctrl}
	mock.recorder = &MockTagRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepo) EXPECT() *MockTagRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockTagRepo) GetByID(ctx context.Context, id, userID string) (model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, userID)
	ret0, _ := ret[0].(model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTagRepoMockRecorder) GetByID(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTagRepo)(nil).GetByID), ctx, id, userID)
}

// ListByUser mocks base method.
func (m *MockTagRepo) ListByUser(ctx context.Context, userID, q string) ([]model.TagWithCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, q)
	ret0, _ := ret[0].([]model.TagWithCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockTagRepoMockRecorder) ListByUser(ctx, userID, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockTagRepo)(nil).ListByUser), ctx, userID, q)
}

// ListForTransaction mocks base method.
func (m *MockTagRepo) ListForTransaction(ctx context.Context, txID string) ([]model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForTransaction", ctx, txID)
	ret0, _ := ret[0].([]model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForTransaction indicates an expected call of ListForTransaction.
func (mr *MockTagRepoMockRecorder) ListForTransaction(ctx, txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForTransaction", reflect.TypeOf((*MockTagRepo)(nil).ListForTransaction), ctx, txID)
}

// SoftDelete mocks base method.
func (m *MockTagRepo) SoftDelete(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockTagRepoMockRecorder) SoftDelete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockTagRepo)(nil).SoftDelete), ctx, id, userID)
}

// Update mocks base method.
func (m *MockTagRepo) Update(ctx context.Context, t model.Tag) (model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, t)
	ret0, _ := ret[0].(model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTagRepoMockRecorder) Update(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTagRepo)(nil).Update), ctx, t)
}

// UpsertForTransaction mocks base method.
func (m *MockTagRepo) UpsertForTransaction(ctx context.Context, txID, userID string, names []string) ([]model.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertForTransaction", ctx, txID, userID, names)
	ret0, _ := ret[0].([]model.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertForTransaction indicates an expected call of UpsertForTransaction.
func (mr *MockTagRepoMockRecorder) UpsertForTransaction(ctx, txID, userID, names any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertForTransaction", reflect.TypeOf((*MockTagRepo)(nil).UpsertForTransaction), ctx, txID, userID, names)
}
