// Code generated by MockGen. DO NOT EDIT.
// Source: monefy_import.go
//
// Generated by this command:
//
//	mockgen -source=monefy_import.go -destination=mocks/mock_import.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockimportRepo is a mock of importRepo interface.
type MockimportRepo struct {
	ctrl     *gomock.Controller
	recorder *MockimportRepoMockRecorder
	isgomock struct{}
}

// MockimportRepoMockRecorder is the mock recorder for MockimportRepo.
type MockimportRepoMockRecorder struct {
	mock *MockimportRepo
}

// NewMockimportRepo creates a new mock instance.
func NewMockimportRepo(ctrl *gomock.Controller) *MockimportRepo {
	mock := &MockimportRepo{ctrl: ctrl}
	mock.recorder = &MockimportRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockimportRepo) EXPECT() *MockimportRepoMockRecorder {
	return m.recorder
}

// Availability mocks base method.
func (m *MockimportRepo) Availability(arg0 context.Context, arg1 string) (model.ImportAvailability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Availability", arg0, arg1)
	ret0, _ := ret[0].(model.ImportAvailability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Availability indicates an expected call of Availability.
func (mr *MockimportRepoMockRecorder) Availability(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Availability", reflect.TypeOf((*MockimportRepo)(nil).Availability), arg0, arg1)
}

// Catalog mocks base method.
func (m *MockimportRepo) Catalog(arg0 context.Context, arg1 bool) ([]model.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Catalog", arg0, arg1)
	ret0, _ := ret[0].([]model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Catalog indicates an expected call of Catalog.
func (mr *MockimportRepoMockRecorder) Catalog(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Catalog", reflect.TypeOf((*MockimportRepo)(nil).Catalog), arg0, arg1)
}

// Currencies mocks base method.
func (m *MockimportRepo) Currencies(arg0 context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Currencies", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Currencies indicates an expected call of Currencies.
func (mr *MockimportRepoMockRecorder) Currencies(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Currencies", reflect.TypeOf((*MockimportRepo)(nil).Currencies), arg0)
}

// DeleteReplacement mocks base method.
func (m *MockimportRepo) DeleteReplacement(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReplacement", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReplacement indicates an expected call of DeleteReplacement.
func (mr *MockimportRepoMockRecorder) DeleteReplacement(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReplacement", reflect.TypeOf((*MockimportRepo)(nil).DeleteReplacement), arg0, arg1)
}

// GetByUsername mocks base method.
func (m *MockimportRepo) GetByUsername(arg0 context.Context, arg1 string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", arg0, arg1)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockimportRepoMockRecorder) GetByUsername(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockimportRepo)(nil).GetByUsername), arg0, arg1)
}

// LockReplacement mocks base method.
func (m *MockimportRepo) LockReplacement(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockReplacement", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockReplacement indicates an expected call of LockReplacement.
func (mr *MockimportRepoMockRecorder) LockReplacement(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockReplacement", reflect.TypeOf((*MockimportRepo)(nil).LockReplacement), arg0)
}

// LockUser mocks base method.
func (m *MockimportRepo) LockUser(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockUser indicates an expected call of LockUser.
func (mr *MockimportRepoMockRecorder) LockUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockUser", reflect.TypeOf((*MockimportRepo)(nil).LockUser), arg0, arg1)
}

// Receipt mocks base method.
func (m *MockimportRepo) Receipt(arg0 context.Context, arg1, arg2 string) (model.ImportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Receipt", arg0, arg1, arg2)
	ret0, _ := ret[0].(model.ImportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Receipt indicates an expected call of Receipt.
func (mr *MockimportRepoMockRecorder) Receipt(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Receipt", reflect.TypeOf((*MockimportRepo)(nil).Receipt), arg0, arg1, arg2)
}

// Replacement mocks base method.
func (m *MockimportRepo) Replacement(arg0 context.Context, arg1 string) (model.ImportReplacement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replacement", arg0, arg1)
	ret0, _ := ret[0].(model.ImportReplacement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replacement indicates an expected call of Replacement.
func (mr *MockimportRepoMockRecorder) Replacement(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replacement", reflect.TypeOf((*MockimportRepo)(nil).Replacement), arg0, arg1)
}

// Write mocks base method.
func (m *MockimportRepo) Write(arg0 context.Context, arg1 model.ImportPreview) (model.ImportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0, arg1)
	ret0, _ := ret[0].(model.ImportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockimportRepoMockRecorder) Write(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockimportRepo)(nil).Write), arg0, arg1)
}

// MockimportStore is a mock of importStore interface.
type MockimportStore struct {
	ctrl     *gomock.Controller
	recorder *MockimportStoreMockRecorder
	isgomock struct{}
}

// MockimportStoreMockRecorder is the mock recorder for MockimportStore.
type MockimportStoreMockRecorder struct {
	mock *MockimportStore
}

// NewMockimportStore creates a new mock instance.
func NewMockimportStore(ctrl *gomock.Controller) *MockimportStore {
	mock := &MockimportStore{ctrl: ctrl}
	mock.recorder = &MockimportStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockimportStore) EXPECT() *MockimportStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockimportStore) Delete(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockimportStoreMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockimportStore)(nil).Delete), arg0, arg1)
}

// Load mocks base method.
func (m *MockimportStore) Load(arg0, arg1 string) (model.ImportPreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", arg0, arg1)
	ret0, _ := ret[0].(model.ImportPreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockimportStoreMockRecorder) Load(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockimportStore)(nil).Load), arg0, arg1)
}

// Save mocks base method.
func (m *MockimportStore) Save(arg0 model.ImportPreview) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockimportStoreMockRecorder) Save(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockimportStore)(nil).Save), arg0)
}
