// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/co-wallet/backend/internal/service (interfaces: CategoryRepo)
//
// Generated by this command:
//
//	mockgen -destination=internal/service/mocks/mock_category_repo.go -package=mocks github.com/co-wallet/backend/internal/service CategoryRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockCategoryRepo is a mock of CategoryRepo interface.
type MockCategoryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryRepoMockRecorder
	isgomock struct{}
}

// MockCategoryRepoMockRecorder is the mock recorder for MockCategoryRepo.
type MockCategoryRepoMockRecorder struct {
	mock *MockCategoryRepo
}

// NewMockCategoryRepo creates a new mock instance.
func NewMockCategoryRepo(ctrl *gomock.Controller) *MockCategoryRepo {
	mock := &MockCategoryRepo{ctrl: ctrl}
	mock.recorder = &MockCategoryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryRepo) EXPECT() *MockCategoryRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCategoryRepo) Create(ctx context.Context, c model.Category) (model.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, c)
	ret0, _ := ret[0].(model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCategoryRepoMockRecorder) Create(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCategoryRepo)(nil).Create), ctx, c)
}

// GetByID mocks base method.
func (m *MockCategoryRepo) GetByID(ctx context.Context, id, userID string) (model.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, userID)
	ret0, _ := ret[0].(model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCategoryRepoMockRecorder) GetByID(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCategoryRepo)(nil).GetByID), ctx, id, userID)
}

// HardDelete mocks base method.
func (m *MockCategoryRepo) HardDelete(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDelete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDelete indicates an expected call of HardDelete.
func (mr *MockCategoryRepoMockRecorder) HardDelete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDelete", reflect.TypeOf((*MockCategoryRepo)(nil).HardDelete), ctx, id, userID)
}

// HasChildren mocks base method.
func (m *MockCategoryRepo) HasChildren(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasChildren", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasChildren indicates an expected call of HasChildren.
func (mr *MockCategoryRepoMockRecorder) HasChildren(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasChildren", reflect.TypeOf((*MockCategoryRepo)(nil).HasChildren), ctx, id)
}

// HasTransactions mocks base method.
func (m *MockCategoryRepo) HasTransactions(ctx context.Context, id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTransactions", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasTransactions indicates an expected call of HasTransactions.
func (mr *MockCategoryRepoMockRecorder) HasTransactions(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTransactions", reflect.TypeOf((*MockCategoryRepo)(nil).HasTransactions), ctx, id)
}

// ListByUser mocks base method.
func (m *MockCategoryRepo) ListByUser(ctx context.Context, userID string, catType model.CategoryType) ([]model.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, catType)
	ret0, _ := ret[0].([]model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockCategoryRepoMockRecorder) ListByUser(ctx, userID, catType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockCategoryRepo)(nil).ListByUser), ctx, userID, catType)
}

// SoftDelete mocks base method.
func (m *MockCategoryRepo) SoftDelete(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockCategoryRepoMockRecorder) SoftDelete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockCategoryRepo)(nil).SoftDelete), ctx, id, userID)
}

// Update mocks base method.
func (m *MockCategoryRepo) Update(ctx context.Context, c model.Category) (model.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, c)
	ret0, _ := ret[0].(model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCategoryRepoMockRecorder) Update(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCategoryRepo)(nil).Update), ctx, c)
}
