// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=mocks/mock_auth_user_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockauthUserRepo is a mock of authUserRepo interface.
type MockauthUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockauthUserRepoMockRecorder
	isgomock struct{}
}

// MockauthUserRepoMockRecorder is the mock recorder for MockauthUserRepo.
type MockauthUserRepoMockRecorder struct {
	mock *MockauthUserRepo
}

// NewMockauthUserRepo creates a new mock instance.
func NewMockauthUserRepo(ctrl *gomock.Controller) *MockauthUserRepo {
	mock := &MockauthUserRepo{ctrl: ctrl}
	mock.recorder = &MockauthUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthUserRepo) EXPECT() *MockauthUserRepoMockRecorder {
	return m.recorder
}

// GetByEmail mocks base method.
func (m *MockauthUserRepo) GetByEmail(ctx context.Context, email string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockauthUserRepoMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockauthUserRepo)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockauthUserRepo) GetByID(ctx context.Context, id string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockauthUserRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockauthUserRepo)(nil).GetByID), ctx, id)
}
