// Code generated by MockGen. DO NOT EDIT.
// Source: account.go
//
// Generated by this command:
//
//	mockgen -source=account.go -destination=mocks/mock_account_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockaccountRepo is a mock of accountRepo interface.
type MockaccountRepo struct {
	ctrl     *gomock.Controller
	recorder *MockaccountRepoMockRecorder
	isgomock struct{}
}

// MockaccountRepoMockRecorder is the mock recorder for MockaccountRepo.
type MockaccountRepoMockRecorder struct {
	mock *MockaccountRepo
}

// NewMockaccountRepo creates a new mock instance.
func NewMockaccountRepo(ctrl *gomock.Controller) *MockaccountRepo {
	mock := &MockaccountRepo{ctrl: ctrl}
	mock.recorder = &MockaccountRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccountRepo) EXPECT() *MockaccountRepoMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m_2 *MockaccountRepo) AddMember(ctx context.Context, m model.AccountMember) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "AddMember", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockaccountRepoMockRecorder) AddMember(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockaccountRepo)(nil).AddMember), ctx, m)
}

// Create mocks base method.
func (m *MockaccountRepo) Create(ctx context.Context, a model.Account) (model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, a)
	ret0, _ := ret[0].(model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockaccountRepoMockRecorder) Create(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockaccountRepo)(nil).Create), ctx, a)
}

// GetByID mocks base method.
func (m *MockaccountRepo) GetByID(ctx context.Context, id string) (model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockaccountRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockaccountRepo)(nil).GetByID), ctx, id)
}

// GetMembers mocks base method.
func (m *MockaccountRepo) GetMembers(ctx context.Context, accountID string) ([]model.AccountMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembers", ctx, accountID)
	ret0, _ := ret[0].([]model.AccountMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembers indicates an expected call of GetMembers.
func (mr *MockaccountRepoMockRecorder) GetMembers(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembers", reflect.TypeOf((*MockaccountRepo)(nil).GetMembers), ctx, accountID)
}

// ListBalancesByUser mocks base method.
func (m *MockaccountRepo) ListBalancesByUser(ctx context.Context, userID, displayCurrency string) (map[string]model.AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBalancesByUser", ctx, userID, displayCurrency)
	ret0, _ := ret[0].(map[string]model.AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBalancesByUser indicates an expected call of ListBalancesByUser.
func (mr *MockaccountRepoMockRecorder) ListBalancesByUser(ctx, userID, displayCurrency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBalancesByUser", reflect.TypeOf((*MockaccountRepo)(nil).ListBalancesByUser), ctx, userID, displayCurrency)
}

// ListByUser mocks base method.
func (m *MockaccountRepo) ListByUser(ctx context.Context, userID string) ([]model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockaccountRepoMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockaccountRepo)(nil).ListByUser), ctx, userID)
}

// RemoveMember mocks base method.
func (m *MockaccountRepo) RemoveMember(ctx context.Context, accountID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, accountID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockaccountRepoMockRecorder) RemoveMember(ctx, accountID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockaccountRepo)(nil).RemoveMember), ctx, accountID, userID)
}

// SoftDelete mocks base method.
func (m *MockaccountRepo) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockaccountRepoMockRecorder) SoftDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockaccountRepo)(nil).SoftDelete), ctx, id)
}

// Update mocks base method.
func (m *MockaccountRepo) Update(ctx context.Context, a model.Account) (model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, a)
	ret0, _ := ret[0].(model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockaccountRepoMockRecorder) Update(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockaccountRepo)(nil).Update), ctx, a)
}

// UpdateMemberShare mocks base method.
func (m *MockaccountRepo) UpdateMemberShare(ctx context.Context, accountID, userID string, share float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberShare", ctx, accountID, userID, share)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMemberShare indicates an expected call of UpdateMemberShare.
func (mr *MockaccountRepoMockRecorder) UpdateMemberShare(ctx, accountID, userID, share any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberShare", reflect.TypeOf((*MockaccountRepo)(nil).UpdateMemberShare), ctx, accountID, userID, share)
}

// MockaccountUserRepo is a mock of accountUserRepo interface.
type MockaccountUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockaccountUserRepoMockRecorder
	isgomock struct{}
}

// MockaccountUserRepoMockRecorder is the mock recorder for MockaccountUserRepo.
type MockaccountUserRepoMockRecorder struct {
	mock *MockaccountUserRepo
}

// NewMockaccountUserRepo creates a new mock instance.
func NewMockaccountUserRepo(ctrl *gomock.Controller) *MockaccountUserRepo {
	mock := &MockaccountUserRepo{ctrl: ctrl}
	mock.recorder = &MockaccountUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockaccountUserRepo) EXPECT() *MockaccountUserRepoMockRecorder {
	return m.recorder
}

// GetByUsername mocks base method.
func (m *MockaccountUserRepo) GetByUsername(ctx context.Context, username string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockaccountUserRepoMockRecorder) GetByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockaccountUserRepo)(nil).GetByUsername), ctx, username)
}
