// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/co-wallet/backend/internal/service (interfaces: AccountRepoForTx)
//
// Generated by this command:
//
//	mockgen -destination=internal/service/mocks/mock_account_repo_tx.go -package=mocks github.com/co-wallet/backend/internal/service AccountRepoForTx
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountRepoForTx is a mock of AccountRepoForTx interface.
type MockAccountRepoForTx struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepoForTxMockRecorder
	isgomock struct{}
}

// MockAccountRepoForTxMockRecorder is the mock recorder for MockAccountRepoForTx.
type MockAccountRepoForTxMockRecorder struct {
	mock *MockAccountRepoForTx
}

// NewMockAccountRepoForTx creates a new mock instance.
func NewMockAccountRepoForTx(ctrl *gomock.Controller) *MockAccountRepoForTx {
	mock := &MockAccountRepoForTx{ctrl: ctrl}
	mock.recorder = &MockAccountRepoForTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepoForTx) EXPECT() *MockAccountRepoForTxMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockAccountRepoForTx) GetByID(ctx context.Context, id string) (model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAccountRepoForTxMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAccountRepoForTx)(nil).GetByID), ctx, id)
}

// IsMember mocks base method.
func (m *MockAccountRepoForTx) IsMember(ctx context.Context, accountID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMember", ctx, accountID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMember indicates an expected call of IsMember.
func (mr *MockAccountRepoForTxMockRecorder) IsMember(ctx, accountID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMember", reflect.TypeOf((*MockAccountRepoForTx)(nil).IsMember), ctx, accountID, userID)
}
