// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/category/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/category/handler.go -destination=internal/handler/category/mocks/mock_category_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	service "github.com/co-wallet/backend/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockcategoryService is a mock of categoryService interface.
type MockcategoryService struct {
	ctrl     *gomock.Controller
	recorder *MockcategoryServiceMockRecorder
	isgomock struct{}
}

// MockcategoryServiceMockRecorder is the mock recorder for MockcategoryService.
type MockcategoryServiceMockRecorder struct {
	mock *MockcategoryService
}

// NewMockcategoryService creates a new mock instance.
func NewMockcategoryService(ctrl *gomock.Controller) *MockcategoryService {
	mock := &MockcategoryService{ctrl: ctrl}
	mock.recorder = &MockcategoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcategoryService) EXPECT() *MockcategoryServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockcategoryService) Create(ctx context.Context, userID string, req model.CreateCategoryReq) (model.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, req)
	ret0, _ := ret[0].(model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockcategoryServiceMockRecorder) Create(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockcategoryService)(nil).Create), ctx, userID, req)
}

// Delete mocks base method.
func (m *MockcategoryService) Delete(ctx context.Context, userID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockcategoryServiceMockRecorder) Delete(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockcategoryService)(nil).Delete), ctx, userID, id)
}

// List mocks base method.
func (m *MockcategoryService) List(ctx context.Context, userID string, catType model.CategoryType) ([]service.CategoryNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, catType)
	ret0, _ := ret[0].([]service.CategoryNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockcategoryServiceMockRecorder) List(ctx, userID, catType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockcategoryService)(nil).List), ctx, userID, catType)
}

// Update mocks base method.
func (m *MockcategoryService) Update(ctx context.Context, userID, id string, req model.UpdateCategoryReq) (model.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userID, id, req)
	ret0, _ := ret[0].(model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockcategoryServiceMockRecorder) Update(ctx, userID, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockcategoryService)(nil).Update), ctx, userID, id, req)
}
