// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/analytics/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/analytics/handler.go -destination=internal/handler/analytics/mocks/mock_analytics_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockanalyticsService is a mock of analyticsService interface.
type MockanalyticsService struct {
	ctrl     *gomock.Controller
	recorder *MockanalyticsServiceMockRecorder
	isgomock struct{}
}

// MockanalyticsServiceMockRecorder is the mock recorder for MockanalyticsService.
type MockanalyticsServiceMockRecorder struct {
	mock *MockanalyticsService
}

// NewMockanalyticsService creates a new mock instance.
func NewMockanalyticsService(ctrl *gomock.Controller) *MockanalyticsService {
	mock := &MockanalyticsService{ctrl: ctrl}
	mock.recorder = &MockanalyticsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockanalyticsService) EXPECT() *MockanalyticsServiceMockRecorder {
	return m.recorder
}

// ByCategory mocks base method.
func (m *MockanalyticsService) ByCategory(ctx context.Context, f model.AnalyticsFilter) ([]model.CategoryStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByCategory", ctx, f)
	ret0, _ := ret[0].([]model.CategoryStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByCategory indicates an expected call of ByCategory.
func (mr *MockanalyticsServiceMockRecorder) ByCategory(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByCategory", reflect.TypeOf((*MockanalyticsService)(nil).ByCategory), ctx, f)
}

// ByTag mocks base method.
func (m *MockanalyticsService) ByTag(ctx context.Context, f model.AnalyticsFilter) ([]model.TagStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByTag", ctx, f)
	ret0, _ := ret[0].([]model.TagStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByTag indicates an expected call of ByTag.
func (mr *MockanalyticsServiceMockRecorder) ByTag(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByTag", reflect.TypeOf((*MockanalyticsService)(nil).ByTag), ctx, f)
}

// Summary mocks base method.
func (m *MockanalyticsService) Summary(ctx context.Context, f model.AnalyticsFilter) (model.AnalyticsSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summary", ctx, f)
	ret0, _ := ret[0].(model.AnalyticsSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summary indicates an expected call of Summary.
func (mr *MockanalyticsServiceMockRecorder) Summary(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summary", reflect.TypeOf((*MockanalyticsService)(nil).Summary), ctx, f)
}

// MockuserSource is a mock of userSource interface.
type MockuserSource struct {
	ctrl     *gomock.Controller
	recorder *MockuserSourceMockRecorder
	isgomock struct{}
}

// MockuserSourceMockRecorder is the mock recorder for MockuserSource.
type MockuserSourceMockRecorder struct {
	mock *MockuserSource
}

// NewMockuserSource creates a new mock instance.
func NewMockuserSource(ctrl *gomock.Controller) *MockuserSource {
	mock := &MockuserSource{ctrl: ctrl}
	mock.recorder = &MockuserSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserSource) EXPECT() *MockuserSourceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockuserSource) GetByID(ctx context.Context, id string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockuserSourceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockuserSource)(nil).GetByID), ctx, id)
}
