// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/currency/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/currency/handler.go -destination=internal/handler/currency/mocks/mock_currency_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockcurrencyService is a mock of currencyService interface.
type MockcurrencyService struct {
	ctrl     *gomock.Controller
	recorder *MockcurrencyServiceMockRecorder
	isgomock struct{}
}

// MockcurrencyServiceMockRecorder is the mock recorder for MockcurrencyService.
type MockcurrencyServiceMockRecorder struct {
	mock *MockcurrencyService
}

// NewMockcurrencyService creates a new mock instance.
func NewMockcurrencyService(ctrl *gomock.Controller) *MockcurrencyService {
	mock := &MockcurrencyService{ctrl: ctrl}
	mock.recorder = &MockcurrencyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcurrencyService) EXPECT() *MockcurrencyServiceMockRecorder {
	return m.recorder
}

// ListActive mocks base method.
func (m *MockcurrencyService) ListActive(ctx context.Context, extraCodes []string) ([]model.CurrencyWithRate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx, extraCodes)
	ret0, _ := ret[0].([]model.CurrencyWithRate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockcurrencyServiceMockRecorder) ListActive(ctx, extraCodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockcurrencyService)(nil).ListActive), ctx, extraCodes)
}
