// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/transaction/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/transaction/handler.go -destination=internal/handler/transaction/mocks/mock_transaction_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/co-wallet/backend/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MocktransactionService is a mock of transactionService interface.
type MocktransactionService struct {
	ctrl     *gomock.Controller
	recorder *MocktransactionServiceMockRecorder
	isgomock struct{}
}

// MocktransactionServiceMockRecorder is the mock recorder for MocktransactionService.
type MocktransactionServiceMockRecorder struct {
	mock *MocktransactionService
}

// NewMocktransactionService creates a new mock instance.
func NewMocktransactionService(ctrl *gomock.Controller) *MocktransactionService {
	mock := &MocktransactionService{ctrl: ctrl}
	mock.recorder = &MocktransactionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktransactionService) EXPECT() *MocktransactionServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocktransactionService) Create(ctx context.Context, userID string, req model.CreateTransactionReq) (model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, req)
	ret0, _ := ret[0].(model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MocktransactionServiceMockRecorder) Create(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocktransactionService)(nil).Create), ctx, userID, req)
}

// Delete mocks base method.
func (m *MocktransactionService) Delete(ctx context.Context, userID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MocktransactionServiceMockRecorder) Delete(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MocktransactionService)(nil).Delete), ctx, userID, id)
}

// GetByID mocks base method.
func (m *MocktransactionService) GetByID(ctx context.Context, userID, id string) (model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID, id)
	ret0, _ := ret[0].(model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MocktransactionServiceMockRecorder) GetByID(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MocktransactionService)(nil).GetByID), ctx, userID, id)
}

// List mocks base method.
func (m *MocktransactionService) List(ctx context.Context, userID string, f model.TransactionFilter) ([]model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, f)
	ret0, _ := ret[0].([]model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MocktransactionServiceMockRecorder) List(ctx, userID, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MocktransactionService)(nil).List), ctx, userID, f)
}

// Update mocks base method.
func (m *MocktransactionService) Update(ctx context.Context, userID, id string, req model.UpdateTransactionReq) (model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userID, id, req)
	ret0, _ := ret[0].(model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MocktransactionServiceMockRecorder) Update(ctx, userID, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MocktransactionService)(nil).Update), ctx, userID, id, req)
}
