// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=mocks/mock_token_validator.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	service "github.com/co-wallet/backend/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MocktokenValidator is a mock of tokenValidator interface.
type MocktokenValidator struct {
	ctrl     *gomock.Controller
	recorder *MocktokenValidatorMockRecorder
	isgomock struct{}
}

// MocktokenValidatorMockRecorder is the mock recorder for MocktokenValidator.
type MocktokenValidatorMockRecorder struct {
	mock *MocktokenValidator
}

// NewMocktokenValidator creates a new mock instance.
func NewMocktokenValidator(ctrl *gomock.Controller) *MocktokenValidator {
	mock := &MocktokenValidator{ctrl: ctrl}
	mock.recorder = &MocktokenValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenValidator) EXPECT() *MocktokenValidatorMockRecorder {
	return m.recorder
}

// ValidateAccessToken mocks base method.
func (m *MocktokenValidator) ValidateAccessToken(token string) (*service.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAccessToken", token)
	ret0, _ := ret[0].(*service.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAccessToken indicates an expected call of ValidateAccessToken.
func (mr *MocktokenValidatorMockRecorder) ValidateAccessToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAccessToken", reflect.TypeOf((*MocktokenValidator)(nil).ValidateAccessToken), token)
}
