// Code generated by MockGen. DO NOT EDIT.
// Source: account.go
//
// Generated by this command:
//
//	mockgen -source=account.go -destination=mocks/mock_member_checker.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockmemberChecker is a mock of memberChecker interface.
type MockmemberChecker struct {
	ctrl     *gomock.Controller
	recorder *MockmemberCheckerMockRecorder
	isgomock struct{}
}

// MockmemberCheckerMockRecorder is the mock recorder for MockmemberChecker.
type MockmemberCheckerMockRecorder struct {
	mock *MockmemberChecker
}

// NewMockmemberChecker creates a new mock instance.
func NewMockmemberChecker(ctrl *gomock.Controller) *MockmemberChecker {
	mock := &MockmemberChecker{ctrl: ctrl}
	mock.recorder = &MockmemberCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmemberChecker) EXPECT() *MockmemberCheckerMockRecorder {
	return m.recorder
}

// IsMember mocks base method.
func (m *MockmemberChecker) IsMember(ctx context.Context, accountID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMember", ctx, accountID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMember indicates an expected call of IsMember.
func (mr *MockmemberCheckerMockRecorder) IsMember(ctx, accountID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMember", reflect.TypeOf((*MockmemberChecker)(nil).IsMember), ctx, accountID, userID)
}
